//
// BrandEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrandEvent: Codable {

    public enum EventId: String, Codable { 
        case click = "brand_click"
    }
    public var brandImressionId: String?
    public var eventId: EventId?

    public init(brandImressionId: String?, eventId: EventId?) {
        self.brandImressionId = brandImressionId
        self.eventId = eventId
    }

    public enum CodingKeys: String, CodingKey { 
        case brandImressionId = "brand_imression_id"
        case eventId = "event_id"
    }

}

