//
// Brand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Brand: Codable {

    public var _id: Int?
    public var name: String?
    public var loginUrl: String?
    public var logo: String?
    public var image: String?
    public var isFavorite: Bool?
    public var highlighted: Bool?
    public var notificationBadge: NotificationBadge?

    public init(_id: Int?, name: String?, loginUrl: String?, logo: String?, image: String?, isFavorite: Bool?, highlighted: Bool?, notificationBadge: NotificationBadge?) {
        self._id = _id
        self.name = name
        self.loginUrl = loginUrl
        self.logo = logo
        self.image = image
        self.isFavorite = isFavorite
        self.highlighted = highlighted
        self.notificationBadge = notificationBadge
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case loginUrl = "login_url"
        case logo
        case image
        case isFavorite = "is_favorite"
        case highlighted
        case notificationBadge = "notification_badge"
    }

}

