//
// DeviceSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceSettings: Codable {

    /** The URL that will be displayed on the error screen */
    public var backUrl: String?

    public init(backUrl: String?) {
        self.backUrl = backUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case backUrl = "back_url"
    }

}

