//
// DeviceTrackingDataLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceTrackingDataLocation: Codable {

    public var latitude: BigDecimal?
    public var longitude: BigDecimal?

    public init(latitude: BigDecimal?, longitude: BigDecimal?) {
        self.latitude = latitude
        self.longitude = longitude
    }


}

