//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var brand: Brand?
    public var impression: BrandImpression?

    public init(brand: Brand?, impression: BrandImpression?) {
        self.brand = brand
        self.impression = impression
    }


}

