//
// Account.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Account: Codable {

    public enum Gender: Int, Codable { 
        case _1 = 1
        case _2 = 2
    }
    public enum Seeking: Int, Codable { 
        case _1 = 1
        case _2 = 2
    }
    public enum BodyType: Int, Codable { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
        case _5 = 5
    }
    public enum MaritalStatus: Int, Codable { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
    }
    public enum Race: Int, Codable { 
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
        case _5 = 5
        case _6 = 6
        case _7 = 7
        case _8 = 8
    }
    public var _id: UUID?
    public var email: String?
    public var username: String?
    public var password: String?
    public var age: Int?
    /** 1 - man 2 - woman */
    public var gender: Gender?
    /** 1 - man 2 - woman */
    public var seeking: Seeking?
    public var zip: Int?
    /** 1 - Slim/Slender 2 - Average 3 - Athletic 4 - More to Love 5 - Large */
    public var bodyType: BodyType?
    /** 1 - Single 2 - Married 3 - Swinger 4 - Divorced */
    public var maritalStatus: MaritalStatus?
    /** 1 - Black 2 - Asian 3 - White 4 - Native American 5 - Latino 6 - Middle eastern 7 - Other 8 - Will tell you later */
    public var race: Race?
    /** Plain Text (up to 60 chars) */
    public var prHeader: String?
    /** Plain Text (up to 750 chars) */
    public var generalInfo: String?

    public init(_id: UUID?, email: String?, username: String?, password: String?, age: Int?, gender: Gender?, seeking: Seeking?, zip: Int?, bodyType: BodyType?, maritalStatus: MaritalStatus?, race: Race?, prHeader: String?, generalInfo: String?) {
        self._id = _id
        self.email = email
        self.username = username
        self.password = password
        self.age = age
        self.gender = gender
        self.seeking = seeking
        self.zip = zip
        self.bodyType = bodyType
        self.maritalStatus = maritalStatus
        self.race = race
        self.prHeader = prHeader
        self.generalInfo = generalInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case email
        case username
        case password
        case age
        case gender
        case seeking
        case zip
        case bodyType = "body_type"
        case maritalStatus = "marital_status"
        case race
        case prHeader = "pr_header"
        case generalInfo = "general_info"
    }

}

