//
// AppEvent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppEvent: Codable {

    public enum EventId: String, Codable { 
        case _open = "app_open"
        case sessionStart = "app_session_start"
        case sessionBackground = "app_session_background"
        case sessionEnd = "app_session_end"
        case error = "app_error"
    }
    public var deviceId: UUID?
    public var eventId: EventId?
    public var data: JSONValue?

    public init(deviceId: UUID?, eventId: EventId?, data: JSONValue?) {
        self.deviceId = deviceId
        self.eventId = eventId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case deviceId = "device_id"
        case eventId = "event_id"
        case data
    }

}

