//
// BrandImpression.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BrandImpression: Codable {

    public var _id: String?
    public var position: Int?

    public init(_id: String?, position: Int?) {
        self._id = _id
        self.position = position
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case position
    }

}

