//
// DeviceTrackingDataDeviceDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceTrackingDataDeviceDetails: Codable {

    public var brand: String?
    public var model: String?
    public var os: String?
    public var osVersion: String?

    public init(brand: String?, model: String?, os: String?, osVersion: String?) {
        self.brand = brand
        self.model = model
        self.os = os
        self.osVersion = osVersion
    }

    public enum CodingKeys: String, CodingKey { 
        case brand
        case model
        case os
        case osVersion = "os_version"
    }

}

