//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Device: Codable {

    /** Unique device identifier generated on server side */
    public var _id: UUID?
    /** Сlient secret key used for authorization */
    public var clientSecret: String?
    public var settings: DeviceSettings?
    public var trackingData: DeviceTrackingData?

    public init(_id: UUID?, clientSecret: String?, settings: DeviceSettings?, trackingData: DeviceTrackingData?) {
        self._id = _id
        self.clientSecret = clientSecret
        self.settings = settings
        self.trackingData = trackingData
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case clientSecret = "client_secret"
        case settings
        case trackingData
    }

}

