//
// DeviceTrackingData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceTrackingData: Codable {

    public var idfa: String?
    public var kochavaDeviceId: String?
    public var onesingalPlayerId: String?
    public var deviceDetails: DeviceTrackingDataDeviceDetails?
    /** ISO language code */
    public var language: String?
    /** ISO 3166 Alpaha3 country code */
    public var country: String?
    public var location: DeviceTrackingDataLocation?

    public init(idfa: String?, kochavaDeviceId: String?, onesingalPlayerId: String?, deviceDetails: DeviceTrackingDataDeviceDetails?, language: String?, country: String?, location: DeviceTrackingDataLocation?) {
        self.idfa = idfa
        self.kochavaDeviceId = kochavaDeviceId
        self.onesingalPlayerId = onesingalPlayerId
        self.deviceDetails = deviceDetails
        self.language = language
        self.country = country
        self.location = location
    }

    public enum CodingKeys: String, CodingKey { 
        case idfa
        case kochavaDeviceId = "kochava_device_id"
        case onesingalPlayerId = "onesingal_player_id"
        case deviceDetails
        case language
        case country
        case location
    }

}

