//
// InvalidDataResponceErrorsDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InvalidDataResponceErrorsDetails: Codable {

    public var attribute: String?
    public var message: String?

    public init(attribute: String?, message: String?) {
        self.attribute = attribute
        self.message = message
    }


}

