//
// AccountAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class AccountAPI {
    /**
     Delete account

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountDelete(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountDeleteWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete account
     - DELETE /account
     - 

     - OAuth:
       - type: oauth2
       - name: oAuth2

     - returns: RequestBuilder<Void> 
     */
    open class func accountDeleteWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/account"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get account details (profile)

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountGet(completion: @escaping ((_ data: Account?,_ error: Error?) -> Void)) {
        accountGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get account details (profile)
     - GET /account
     - 

     - OAuth:
       - type: oauth2
       - name: oAuth2
     - examples: [{contentType=application/json, example={
  "zip" : 27610,
  "gender" : 0,
  "race" : 5,
  "seeking" : 6,
  "pr_header" : "pr_header",
  "password" : "qwerty",
  "marital_status" : 5,
  "body_type" : 1,
  "general_info" : "general_info",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "email" : "",
  "age" : 23,
  "username" : "vasya"
}}]

     - returns: RequestBuilder<Account> 
     */
    open class func accountGetWithRequestBuilder() -> RequestBuilder<Account> {
        let path = "/account"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Account>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Deauthorize account, invalidate access_token

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func accountLogoutPut(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        accountLogoutPutWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Deauthorize account, invalidate access_token
     - PUT /account/logout
     - 

     - OAuth:
       - type: oauth2
       - name: oAuth2

     - returns: RequestBuilder<Void> 
     */
    open class func accountLogoutPutWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/account/logout"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
