//
// TrackingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TrackingAPI {
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func trackAppEventPost(body: AppEvent? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        trackAppEventPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /track/app-event
     - 

     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func trackAppEventPostWithRequestBuilder(body: AppEvent? = nil) -> RequestBuilder<Void> {
        let path = "/track/app-event"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func trackBrandEventPost(body: BrandEvent? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        trackBrandEventPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /track/brand-event
     - 

     - OAuth:
       - type: oauth2
       - name: oAuth2
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func trackBrandEventPostWithRequestBuilder(body: BrandEvent? = nil) -> RequestBuilder<Void> {
        let path = "/track/brand-event"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
